### ISSUE TITLE
读取不了舰娘是什么级的船

### ISSUE THREAD

**Issue by E2VjZHNhLXNoYTItbmlzdHAyNTYIbmlzdHA** [Diablohu/KCTip#1]
![qq 20170814154135](https://user-images.githubusercontent.com/10227804/29288577-3e3a828e-8107-11e7-9615-09184d79f702.png)
这个插件在网站写攻略挺好用的。希望大大能修复一下这个问题。谢谢。

**Comment by Diablohu** [comment]
fixed

**Comment by E2VjZHNhLXNoYTItbmlzdHAyNTYIbmlzdHA** [comment]
谢谢大大！
